[#ftl]
[@b.head/]
[#-- filterable="true"--]
[@b.grid  items=courses var="course" filterable="true"]
  [@b.row]
    [@b.col property="name" title="名称"]
      [#if urlmap[course.id?string]??]<a href="${urlmap[course.id?string]}">${course.name}</a>[#else]None[/#if]
    [/@]
  [/@]
[/@]
[@b.foot/]