[#ftl]
[@b.head/]
[#-- filterable="true"--]
[@b.grid  items=staffs var="staff"]
  [@b.row]
    [@b.col width="30%" property="person.code" title="工号"][/@]
    [@b.col width="30%" property="person.name" title="姓名"][@b.a href="teacher-info!nav?id=${staff.id}"]${(staff.person.name)!}[/@][/@]
    [@b.col width="40%" property="post.head.department.name" title="所属部门"][/@]
  [/@]
[/@]
[@b.foot/]